### ISSUE TITLE
[Feature] visualization for TwoPhotonSeries

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#13] opened 2023-07-07 20:17 UTC
It would be nice to have a visualization for raw imaging data from OnePhotonSeries and TwoPhotonSeries objects that have the data internal to the NWB files. As a first pass we don't even need to play the video, we could just show the selected image and provide a slider for that frame.

https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/147/890/1478902e-b250-4845-8514-6d25a27332f2

<img width="673" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/a6f8c82a-03f4-46c7-a027-7aeeef9c6a56">

Analogous widget in NWB Widgets:

![image](https://github.com/flatironinstitute/neurosift/assets/844306/383e6d5a-bf35-4aa8-9adc-bf5161da6b06)

https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/d62bed037e24c75f8a9215b8f0ab81e975763700/nwbwidgets/ophys.py#L28-L92

**Comment by magland** [comment] 2023-07-11 14:57
Your linked example doesn't load for me. The console message is that it can't load any of the hdf5 groups. Are you sure this is the intended example?

**Comment by CodyCBakerPhD** [comment] 2023-07-11 15:14
I can confirm I cannot stream that asset in Python either - maybe a copy/paste mistake (or embargo?)

I'd also point to the same example as in #21: https://dandiarchive.s3.amazonaws.com/blobs/fae/b55/faeb55de-5809-4a40-a2fe-bd32edad90e4 (DANDI set 000350, file sub-20161022-1/sub-20161022-1_ses-20161022T151003_ophys.nwb)

I'd also love to point towards some improvements I suggested making on the 2P visual in the Widgets, which ultimately got stuck in review limbo but here is a demo video from around that time

https://github.com/flatironinstitute/neurosift/assets/51133164/a7c7800e-1d33-4376-ad58-040852493b85

In particular the manual contrast control is quite important we've found, since automated contrast schemes can leave images far too dark or far too bright and not ideally depict the ROI flourescence

I also later added color scheme selection (the lab we were working with at the time liked 'sunset' style coloration), and wanted to add video animation (for short snippepts) - all of which are all just arguments of `plotly.imshow`, so all the extra controllers (sliders, buttons, etc) were really just wrapping around those arguments

**Comment by bendichter** [comment] 2023-07-12 13:40
This is awesome, @magland ! I just tested it out and it does seem to work. 

For the controls, I find Cody's min and max controller more intuitive than Brightness an Contrast. With your controls, it's not clear what the default should be, particularly since the numeric value of the slider is not visible (does it start at 1.0). It's also not clear precisely how the controls change how data values are mapped to color. With Cody's range controller, it is easy to see how you are controlling this mapping, and straightforward to create good visualizations, so I'd prefer the range controller.

Also, (and this could wait for a future PR) it might be nice to provide the ability to slice the data by a different plane.

**Comment by magland** [comment] 2023-07-13 00:37
@bendichter The brightness and contrast controls have now been replaced by a single dual-slider-control similar to Cody's widget. If it looks good to you, I'll close this issue and we can open other issues for more advanced features.



![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/15e02d37-e296-484d-bd46-61ce2d8ad481)

**Comment by bendichter** [comment] 2023-07-13 00:40
Lgtm!

**Closed** 2023-07-13 12:16 UTC
